### ISSUE TITLE
Dealing with object inheritance

### ISSUE THREAD

**Issue by mcleanl** [mathpere/grails-hibernate-search-plugin#14]
I have a simple class heirarchy like so:

class A {
String name
}

class B  extends A {
String description
String widget
}

I want to index B so that it also contains all the attributes from A. I assumed that I'd do it like so...

class B  extends A {

String description
String widget

static search {
name index:'tokenized'
description index:'tokenized'
widget index:'tokenized'
}

}

however, when I look at the index for B the name from A doesn't exist. No errors/exceptions  thrown.  When I do this outside of grails/plugin it works fine.  Any hint please?

**Comment by lgrignon** [comment]
This is still a bug, I will try to fix it for a 2.1 release

**Comment by lgrignon** [comment]
See the note in this chapter of the doc: https://docs.jboss.org/hibernate/stable/search/reference/en-US/html_single/#_defining_fields_for_indexing 

Inherited properties aren't natively supported, I will try to add support for this in the Grails' plugin

**Comment by lgrignon** [comment]
Fixed in #23
