### ISSUE TITLE
Grails 3 / Hibernate 5 support

### ISSUE THREAD

**Issue by lgrignon** [mathpere/grails-hibernate-search-plugin#20]
Hello, I am trying to migrate your plugin for Grails 3.2, GORM 6 and Hibernate 5. Would you be interested in merging my work if I PR?

Thanks anyway.

**Comment by mathpere** [comment]
Hello,

I currently don't maintain this project. I can quickly read your proposal and give you the right permission to merge your work?

**Comment by lgrignon** [comment]
ok, thanks, I will PR next week, I have to fix some points before being able to merge ;)

**Comment by lgrignon** [comment]
Support added in:
https://github.com/mathpere/grails-hibernate-search-plugin/pull/21
