### ISSUE TITLE
Bean named entityInterceptor that could not be found

### ISSUE THREAD

**Issue by aesteve** [mathpere/grails-hibernate-search-plugin#28]
Hello, and thanks for your work.

I'd like to try your plugin but just after the first step of your README, (=> updating the ` build.gradle` file) my application which is working great if I remove 

```
    compile "org.grails.plugins:hibernate-search:2.0"
```

from the `dependencies` block, fails to start with the following error : 

```
2017-01-30 12:23:13.173 ERROR --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method setConfigurers in org.springframework.transaction.annotation.AbstractTransactionManagementConfiguration required a bean named 'entityInterceptor' that could not be found.


Action:

Consider defining a bean named 'entityInterceptor' in your configuration.
 
```

Where is it mentionned in the documentation ? I can't find where I have to define such bean... 

```
| Grails Version: 3.2.4
| Groovy Version: 2.4.7
| JVM Version: 1.8.0_101
```

Thanks for your help.

**Comment by lgrignon** [comment]
Hello, thanks for using this plugin! Actually it only works with Grails 3.1.x
I must admin this a shame but Grails refactored specifically the datastore / connections API in Grails >= 3.2
If you need this feature badly, maybe you could try to adjust it and PR but it seemed like a non negligible amount of work to me :)

Thanks again for reporting

**Comment by aesteve** [comment]
Oh OK, I don't think I'm able to file a PR though, I'm still at the "week-end experiment" level of Grails knowledge unfortunately.

Hope someone can fix it in the future. Feel free to close the PR if you want to.
