### ISSUE TITLE
Problem running with hibernate5:6.1.4

### ISSUE THREAD

**Issue by lgrignon** [mathpere/grails-hibernate-search-plugin#32]
@betoesquivel wrote:
I managed to get this to work on grails 3 using your example, I just had to downgrade to the version 6.1.3 of hibernate5 since if I set the 6.1.4 it was trying to get the mongodb dependency 6.1.4 (which doesn't exist). I needed mongodb to work because some of my domains are mapped there. However, the ones that I want to search on are not on mongo.

**Comment by lgrignon** [comment]
I managed to make it work on `hibernate5:6.1.4` with `org.grails.plugins:mongodb:6.1.2`
I just had to force the version in the `build.gradle` therefore I might miss something.
I created a branch in the Grails 3 quick start project so you could check the difference with your project:
https://github.com/lgrignon/grails3-quick-start/blob/mongotest/build.gradle#L73

Hope this helped.
Please close issue if you think it's solved

**Comment by betoesquivel** [comment]
This worked, the issue I was having was that I had to clean the dependency cache. All the build/ folders and the .gradle folders. A grails clean didn't  cut it. 

I am marking as solved.

**Comment by betoesquivel** [comment]
I assume I cannot close the issue without a commit, can I?

**Comment by lgrignon** [comment]
Yes, you can close issues without commit but maybe you can't because you didn't create it.
I close this issue and answer to the other
