### ISSUE TITLE
UrlMappings should not be packaged with plugin

### ISSUE THREAD

**Issue by erichmx** [mathpere/grails-hibernate-search-plugin#34]
Hi, The UrlMappings should be excluded from the plugin jar. Or delete the file since the plugin does not need any UrlMapping

It overwrites url mappings of the application.

See also https://github.com/TouK/excel-export/issues/44

**Comment by lgrignon** [comment]
deleted in b83538c976bf770cb670f6c555ee4acdd8b1d386
pushed in 2.1.1 (don't forget to force refresh dependencies please)
Thanks for reporting
